Build image at https://github.com/fantasy-mark/AutoImage/actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,6 +24,13 @@ jobs:
         fi
         
         # 使用Dockerfile构建镜像,推送镜像到镜像仓库 - 对应 https://cr.console.aliyun.com/cn-shenzhen/instance/repositories
-        docker build . --file Dockerfile --tag auto_image/$image_name:latest
+        version="latest"
+        docker build -f dockerfile -t $image_name:${version} .
+        docker tag $image_name:${version} auto_image/$image_name:${version} 
         docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
-        docker push auto_image/$image_name:latest
+        docker push auto_image/$image_name:${version}
+        if [ $? -eq 0 ]; then
+            echo "docker push Success"
+        else 
+            echo "docker push Failed"
+        fi
